// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/port.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// A Port object
type Port struct {
	Id                   string    `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string    `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	City                 string    `protobuf:"bytes,3,opt,name=city,proto3" json:"city,omitempty"`
	Country              string    `protobuf:"bytes,4,opt,name=country,proto3" json:"country,omitempty"`
	Alias                []string  `protobuf:"bytes,5,rep,name=alias,proto3" json:"alias,omitempty"`
	Regions              []string  `protobuf:"bytes,6,rep,name=regions,proto3" json:"regions,omitempty"`
	Coordinates          []float64 `protobuf:"fixed64,7,rep,packed,name=coordinates,proto3" json:"coordinates,omitempty"`
	Province             string    `protobuf:"bytes,8,opt,name=province,proto3" json:"province,omitempty"`
	Timezone             string    `protobuf:"bytes,9,opt,name=timezone,proto3" json:"timezone,omitempty"`
	Unlocs               []string  `protobuf:"bytes,10,rep,name=unlocs,proto3" json:"unlocs,omitempty"`
	Code                 string    `protobuf:"bytes,11,opt,name=code,proto3" json:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Port) Reset()         { *m = Port{} }
func (m *Port) String() string { return proto.CompactTextString(m) }
func (*Port) ProtoMessage()    {}
func (*Port) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f4e75a6050eada6, []int{0}
}

func (m *Port) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Port.Unmarshal(m, b)
}
func (m *Port) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Port.Marshal(b, m, deterministic)
}
func (m *Port) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Port.Merge(m, src)
}
func (m *Port) XXX_Size() int {
	return xxx_messageInfo_Port.Size(m)
}
func (m *Port) XXX_DiscardUnknown() {
	xxx_messageInfo_Port.DiscardUnknown(m)
}

var xxx_messageInfo_Port proto.InternalMessageInfo

func (m *Port) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Port) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Port) GetCity() string {
	if m != nil {
		return m.City
	}
	return ""
}

func (m *Port) GetCountry() string {
	if m != nil {
		return m.Country
	}
	return ""
}

func (m *Port) GetAlias() []string {
	if m != nil {
		return m.Alias
	}
	return nil
}

func (m *Port) GetRegions() []string {
	if m != nil {
		return m.Regions
	}
	return nil
}

func (m *Port) GetCoordinates() []float64 {
	if m != nil {
		return m.Coordinates
	}
	return nil
}

func (m *Port) GetProvince() string {
	if m != nil {
		return m.Province
	}
	return ""
}

func (m *Port) GetTimezone() string {
	if m != nil {
		return m.Timezone
	}
	return ""
}

func (m *Port) GetUnlocs() []string {
	if m != nil {
		return m.Unlocs
	}
	return nil
}

func (m *Port) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

// Used to return an empty response
type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f4e75a6050eada6, []int{1}
}

func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

// Returned by the streaming create and update
type UpdateResponse struct {
	Count                int32    `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateResponse) Reset()         { *m = UpdateResponse{} }
func (m *UpdateResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateResponse) ProtoMessage()    {}
func (*UpdateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f4e75a6050eada6, []int{2}
}

func (m *UpdateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateResponse.Unmarshal(m, b)
}
func (m *UpdateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateResponse.Marshal(b, m, deterministic)
}
func (m *UpdateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateResponse.Merge(m, src)
}
func (m *UpdateResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateResponse.Size(m)
}
func (m *UpdateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateResponse proto.InternalMessageInfo

func (m *UpdateResponse) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

// Passed as an argument to the streaming list method
type ListRequest struct {
	Count                int32    `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListRequest) Reset()         { *m = ListRequest{} }
func (m *ListRequest) String() string { return proto.CompactTextString(m) }
func (*ListRequest) ProtoMessage()    {}
func (*ListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f4e75a6050eada6, []int{3}
}

func (m *ListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListRequest.Unmarshal(m, b)
}
func (m *ListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListRequest.Marshal(b, m, deterministic)
}
func (m *ListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListRequest.Merge(m, src)
}
func (m *ListRequest) XXX_Size() int {
	return xxx_messageInfo_ListRequest.Size(m)
}
func (m *ListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListRequest proto.InternalMessageInfo

func (m *ListRequest) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

func init() {
	proto.RegisterType((*Port)(nil), "proto.Port")
	proto.RegisterType((*Empty)(nil), "proto.Empty")
	proto.RegisterType((*UpdateResponse)(nil), "proto.UpdateResponse")
	proto.RegisterType((*ListRequest)(nil), "proto.ListRequest")
}

func init() { proto.RegisterFile("proto/port.proto", fileDescriptor_7f4e75a6050eada6) }

var fileDescriptor_7f4e75a6050eada6 = []byte{
	// 392 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x92, 0xcf, 0x8e, 0xd3, 0x30,
	0x10, 0xc6, 0x49, 0xda, 0x34, 0x9b, 0x89, 0xb4, 0x02, 0x0b, 0x90, 0xb5, 0xa7, 0x28, 0x08, 0x94,
	0x03, 0x9b, 0xae, 0x96, 0x03, 0x42, 0xdc, 0x60, 0x11, 0x17, 0x0e, 0x28, 0x12, 0x17, 0x6e, 0xd9,
	0x64, 0xb4, 0x58, 0x34, 0x9e, 0x60, 0x3b, 0x45, 0xe5, 0x21, 0x78, 0x25, 0x5e, 0x0d, 0x79, 0x9c,
	0x42, 0xf9, 0x73, 0xd8, 0x9e, 0x3c, 0xbf, 0xcf, 0x33, 0x1d, 0x7f, 0x5f, 0x03, 0x77, 0x47, 0x43,
	0x8e, 0xd6, 0x23, 0x19, 0x57, 0x73, 0x29, 0x12, 0x3e, 0xca, 0xef, 0x31, 0x2c, 0xdf, 0x93, 0x71,
	0xe2, 0x14, 0x62, 0xd5, 0xcb, 0xa8, 0x88, 0xaa, 0xac, 0x89, 0x55, 0x2f, 0x04, 0x2c, 0x75, 0x3b,
	0xa0, 0x8c, 0x59, 0xe1, 0xda, 0x6b, 0x9d, 0x72, 0x3b, 0xb9, 0x08, 0x9a, 0xaf, 0x85, 0x84, 0xb4,
	0xa3, 0x49, 0x3b, 0xb3, 0x93, 0x4b, 0x96, 0xf7, 0x28, 0xee, 0x43, 0xd2, 0x6e, 0x54, 0x6b, 0x65,
	0x52, 0x2c, 0xaa, 0xac, 0x09, 0xe0, 0xfb, 0x0d, 0xde, 0x28, 0xd2, 0x56, 0xae, 0x58, 0xdf, 0xa3,
	0x28, 0x20, 0xef, 0x88, 0x4c, 0xaf, 0x74, 0xeb, 0xd0, 0xca, 0xb4, 0x58, 0x54, 0x51, 0x73, 0x28,
	0x89, 0x33, 0x38, 0x19, 0x0d, 0x6d, 0x95, 0xee, 0x50, 0x9e, 0xf0, 0xb2, 0x5f, 0xec, 0xef, 0x9c,
	0x1a, 0xf0, 0x1b, 0x69, 0x94, 0x59, 0xb8, 0xdb, 0xb3, 0x78, 0x08, 0xab, 0x49, 0x6f, 0xa8, 0xb3,
	0x12, 0x78, 0xe5, 0x4c, 0xec, 0x87, 0x7a, 0x94, 0xf9, 0xec, 0x87, 0x7a, 0x2c, 0x53, 0x48, 0xde,
	0x0c, 0xa3, 0xdb, 0x95, 0x4f, 0xe0, 0xf4, 0xc3, 0xd8, 0xb7, 0x0e, 0x1b, 0xb4, 0x23, 0x69, 0x8b,
	0xde, 0x10, 0x7b, 0xe3, 0x94, 0x92, 0x26, 0x40, 0xf9, 0x08, 0xf2, 0x77, 0xca, 0xba, 0x06, 0xbf,
	0x4c, 0x68, 0xdd, 0xff, 0x9b, 0x2e, 0x7f, 0xc4, 0x90, 0xfb, 0x98, 0xed, 0x15, 0x0d, 0xad, 0xd2,
	0xe2, 0x31, 0xa4, 0x6f, 0xd1, 0x71, 0xf0, 0x79, 0xf8, 0x43, 0x6a, 0x0f, 0x67, 0x87, 0x50, 0xde,
	0x11, 0x97, 0x00, 0xaf, 0x0d, 0xb6, 0x0e, 0xff, 0xed, 0x7c, 0x30, 0xc3, 0x9f, 0x6f, 0x0c, 0x33,
	0x41, 0x3b, 0x6e, 0xe6, 0x0a, 0x37, 0x78, 0xd4, 0xcc, 0x05, 0x64, 0xde, 0x37, 0xbb, 0x12, 0x62,
	0xee, 0x3a, 0x48, 0xe2, 0x2f, 0x2f, 0x17, 0x91, 0x78, 0x09, 0xf7, 0x82, 0x9b, 0xdf, 0xef, 0xb3,
	0xb7, 0x5b, 0x56, 0x45, 0xaf, 0xea, 0x8f, 0x4f, 0x6f, 0x94, 0xfb, 0x34, 0x5d, 0xd7, 0x1d, 0x0d,
	0xeb, 0x41, 0x7d, 0xc6, 0xaf, 0xcf, 0x5f, 0xf0, 0x07, 0x7d, 0xde, 0x73, 0xa6, 0xe7, 0x16, 0xcd,
	0x56, 0x75, 0xb8, 0xe6, 0x9f, 0xb8, 0x5e, 0xf1, 0xf1, 0xec, 0x67, 0x00, 0x00, 0x00, 0xff, 0xff,
	0x54, 0xb7, 0xca, 0xa3, 0xfa, 0x02, 0x00, 0x00,
}
